spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/Library
    username: abinesh
    password: abi
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true


  graphql:
    graphiql:
      enabled: true